SET(CMAKE_SYSTEM_NAME Android)
SET(CMAKE_SYSTEM_VERSION 21)

SET(ANDROID_NDK_ROOT $ENV{ANDROID_NDK_HOME})

IF(NOT ANDROID_NDK_ROOT)
    MESSAGE(FATAL_ERROR "ANDROID_NDK_HOME environment variable is not set. Please set it to the path of your Android NDK.")
ENDIF()

SET(CMAKE_ANDROID_NDK ${ANDROID_NDK_ROOT})

SET(CMAKE_TOOLCHAIN_FILE ${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake)

INCLUDE(${CMAKE_TOOLCHAIN_FILE})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)